export { default as getPosts } from "./getPosts.js"
export { default as getPostById } from "./getPostById.js"
export { default as getPostsByImpacter } from "./getPostsByImpacter.js"
export { default as updatePost } from "./updatePost.js"
export { default as savePost } from "./savePost.js"
export { default as deletePost } from "./deletePost.js"
